name: Deploy to Render

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: website-api

jobs:
  docker-build-and-push: 
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Build and push image to Github Container Registry
        run: ./build.sh DockerPush -ImageName ${{ env.IMAGE_NAME }} -GithubToken ${{ secrets.GITHUB_TOKEN }}
        shell: bash