name: Deploy to Render

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  REGISTRY_NAMESPACE: arcticgizmo
  IMAGE_NAME: website-api

jobs:
  docker-build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Build and push image to Github Container Registry
      #   run: ./build.sh DockerPush -ImageName ${{ env.IMAGE_NAME }} -GithubToken ${{ secrets.GITHUB_TOKEN }}
      #   shell: bash

      # - name: Git Version
      #   id: version
      #   uses: codacy/git-version@2.8.0


      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0


      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     tags: |
      #       type=semver,pattern={{version}}
      #     images: ${{ env.REGISTRY_NAMESPACE }}/${{ env.IMAGE_NAME }}

      # - name: Deploy
      #   run: |
      #     curl -G \
      #       --data-urlencode "key=${{ secrets.RENDER_SRV_KEY }}" \
      #       --data-urlencode "imagURL=${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ steps.gitversion.outputs.SemVer }}" \
      #       https://api.render.com/deploy/${{ secrets.RENDER_SRV }}
      #   shell: bash
