name: Deploy to Render

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  REGISTRY_NAMESPACE: arcticgizmo
  IMAGE_NAME: website-api

jobs:
  # docker-build-and-push: 
  #   name: Build & Push Docker Image
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
          
  #     - name: Build and push image to Github Container Registry
  #       run: ./build.sh DockerPush -ImageName ${{ env.IMAGE_NAME }} -GithubToken ${{ secrets.GITHUB_TOKEN }}
  #       shell: bash

  deploy-to-render:
    name: "Trigger deploy on Render"
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          curl -G \
            --data-urlencode "key=${{ secrets.RENDER_SRV_KEY }}" \
            --data-urlencode "imagURL=${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESAPCE }}/${{ env.IMAGE_NAME }}:0.0.6" \
            https://api.render.com/deploy/${{ secrets.RENDER_SRV }}
        shell: bash

