name: Deploy to Render

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  REGISTRY_NAMESPACE: arcticgizmo
  IMAGE_NAME: website-api

jobs:
  docker-build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and push image to Github Container Registry
        run: ./build.sh DockerPush -ImageName ${{ env.IMAGE_NAME }} -GithubToken ${{ secrets.GITHUB_TOKEN }}
        shell: bash

      - name: Deploy to Render
        run: ./build.sh DeployToRender -RenderSrv ${{ secrets.RENDER_SRV }} -REnderSrvKey ${{ secrets.RENDER_SRV_KEY }}
        shell: bash
